spring:
  application:
    name: Server
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
#    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
    url: jdbc:postgresql://localhost:5432/clearcart

  graphql:
    schema:
      locations: classpath:graphql/**/
    graphiql:
      enabled: true
      path: /playground
    http:
      path: /api

#logging:
#  level:
#    org.springframework.graphql: DEBUG

jwt:
  issuer: 'clearcart'
  audience: 'graphql-clients'
  expires-minutes: 3600
  hs256-secret: ahahahhahahahahhahahahahhahahahhaha
